const spb = {
  area_code: '0',
  ip: '212.92.98.95',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'St.-Petersburg',
  country: 'Russia',
  longitude: '30.3096',
  accuracy: 20,
  organization_name: 'OOO Network of data-centers Selectel',
  timezone: 'Europe\/Moscow',
  city: 'St Petersburg',
  organization: 'AS49505 OOO Network of data-centers Selectel',
  asn: 49505,
  latitude: '59.9417',
}
const lenOblast = {
  area_code: '0',
  ip: '5.101.24.4',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'Leningrad Oblast',
  country: 'Russia',
  longitude: '29.0966',
  accuracy: 500,
  organization_name: 'LTD AtelRybinsk',
  timezone: 'Europe\/Moscow',
  city: 'Yablonitsy',
  organization: 'AS201952 LTD AtelRybinsk',
  asn: 201952,
  latitude: '59.2597',
}

const msk = {
  area_code: '0',
  ip: '77.37.184.221',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'Moscow',
  country: 'Russia',
  longitude: '37.6171',
  accuracy: 5,
  organization_name: 'Rostelecom',
  timezone: 'Europe\/Moscow',
  city: 'Moscow',
  organization: 'AS42610 Rostelecom',
  asn: 42610,
  latitude: '55.7483',
}

const mosOblast = {
  area_code: '0',
  ip: '2.92.130.252',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'Moscow Oblast',
  country: 'Russia',
  longitude: '37.9465',
  accuracy: 1000,
  organization_name: 'PVimpelCom',
  timezone: 'Europe\/Moscow',
  city: 'Balashikha',
  organization: 'AS8402 PVimpelCom',
  asn: 8402,
  latitude: '55.8015',
}

const brn = {
  area_code: '0',
  ip: '5.77.16.69',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'Bryansk Oblast',
  country: 'Russia',
  longitude: '34.5043',
  accuracy: 50,
  organization_name: 'JSC ER-Telecom Holding',
  timezone: 'Europe\/Moscow',
  city: 'Navlya',
  organization: 'AS57044 JSC ER-Telecom Holding',
  asn: 57044,
  latitude: '52.8302',
}

const vrn = {
  area_code: '0',
  ip: '2.57.83.194',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'Voronezh Oblast',
  country: 'Russia',
  longitude: '39.1843',
  accuracy: 20,
  organization_name: 'Voronezh Telecom LLC',
  timezone: 'Europe\/Moscow',
  city: 'Voronezh',
  organization: 'AS209206 Voronezh Telecom LLC',
  asn: 209206,
  latitude: '51.672',
}

const kaluga = {
  area_code: '0',
  ip: '2.92.247.95',
  country_code: 'RU',
  country_code3: 'RUS',
  continent_code: 'EU',
  region: 'Kaluga Oblast',
  country: 'Russia',
  longitude: '36.2699',
  accuracy: 1000,
  organization_name: 'PVimpelCom',
  timezone: 'Europe\/Moscow',
  city: 'Kaluga',
  organization: 'AS8402 PVimpelCom',
  asn: 8402,
  latitude: '54.5308',
}
