/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./components/**/*.{js,vue,ts}",
        "./layouts/**/*.vue",
        "./pages/**/*.vue",
        "./plugins/**/*.{js,ts}",
        "./nuxt.config.{js,ts}",
        "./default.vue",
    ],
    theme: {
        extend: {
            colors: {
                'primaryDark': '#141414',
                'secondaryDark': '#211D1D',
                'primaryGrey': '#767676',
                'secondaryGrey': '#ECECEC',
                'white': '#fff'
            },
            fontFamily: {
                sans: [
                    'Ag Helvetica',
                    '"Helvetica Neue"',
                    'Arial',
                    'Roboto',
                    'ui-sans-serif',
                    'system-ui',
                    '-apple-system',
                    'BlinkMacSystemFont',
                    '"Segoe UI"',
                    '"Noto Sans"',
                    'sans-serif',
                    '"Apple Color Emoji"',
                    '"Segoe UI Emoji"',
                    '"Segoe UI Symbol"',
                    '"Noto Color Emoji"',
                ],
                mono: [
                    'abchanel-corpo',
                    'ABChanelCorpoRegular',
                    'Open Sans',
                    'ui-monospace',
                    'SFMono-Regular',
                    'Menlo',
                    'Monaco',
                    'Consolas',
                    '"Liberation Mono"',
                    '"Courier New"',
                    'monospace',
                ],
            },
            fontSize: {
                'h1-xl': ['70px', {lineHeight: '99px'}],
                '50-mono': ['50px', {lineHeight: '71x'}],
                'h2-xl': ['25px', {lineHeight: '35px'}],
                'h3-xl': ['16px', {lineHeight: '23px'}],
                'h4-xl': ['14px', {lineHeight: '20px'}],
                'h5-xl': ['17px', {lineHeight: '20px'}],
                'p-xl': ['17px', {lineHeight: '30px'}],

                'h1-lg': ['60px', {lineHeight: '85px'}],
                '45-mono': ['45px', {lineHeight: '64px'}],
                'h2-lg': ['23px', {lineHeight: '33px'}],
                'h3-lg': ['14px', {lineHeight: '20px'}],
                'h4-lg': ['13px', {lineHeight: '18px'}],
                'h5-lg': ['15px', {lineHeight: '21px'}],
                'p-lg': ['15px', {lineHeight: '25px'}],

                'h1-md': ['30px', {lineHeight: '43px'}],
                'h2-md': ['22px', {lineHeight: '30px'}],
                'h3-md': ['14px', {lineHeight: '20px'}],
                'h4-md': ['13px', {lineHeight: '18px'}],
                'h5-md': ['15px', {lineHeight: '21px'}],
                'p-md': ['15px', {lineHeight: '21px'}],

                'h1-sm': ['29px', {lineHeight: '41px'}],
                'h2-sm': ['23px', {lineHeight: '33px'}],
                'h3-sm': ['14px', {lineHeight: '20px'}],
                'h4-sm': ['13px', {lineHeight: '18px'}],
                'h5-sm': ['15px', {lineHeight: '21px'}],
                'p-sm': ['15px', {lineHeight: '21px'}],
            },
            fontWeight: {
                semibold: 600,
                bold: 700,
                regular: 400,
                'sans-bold': 800,
            },
            screens: {
                sm: '362px',
                md: '770px',
                lg: '1442px',
                xl: '1922px',
            },
            //   container: {
            //     center: true,
            //     display: 'flex',
            //     // maxWidth: {
            //     //   sm: '320px',
            //     //   // sm: '360px',
            //     //   md: '698px',
            //     //   // md: '768px',
            //     //   lg: '1260px',
            //     //   // lg: '1440px',
            //     //   xl: '1454px',
            //     //   // xl: '1920px',
            //     // },
            //     // marginInline: {
            //     //     sm: '20px',
            //     //     md: '35px',
            //     //     lg: '90px',
            //     //     xl: '228px',
            //     // }
            //   },
        },
        plugins: [],
    }
}
