on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_TAG: "latest"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: romanri85/b-les-frontend:latest
          file: docker/Dockerfile
  pull:
    runs-on: ubuntu-latest
    needs: [ push ]
    env:
      DOCKER_CONTAINER_NAME: "b-les-front"
      DOCKER_IMAGE_TAG: "romanri85/b-les-frontend:latest"
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd b-les-front
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker rm -f ${{ env.DOCKER_CONTAINER_NAME }}
            docker rmi -f ${{ env.DOCKER_IMAGE_TAG }}
            docker pull ${{ env.DOCKER_IMAGE_TAG }}
            docker run -p 3000:3000 -d -it --restart always --name ${{ env.DOCKER_CONTAINER_NAME }} ${{ env.DOCKER_IMAGE_TAG }}
            docker logout